package com.personalcoacher.domain.model

import java.time.Instant

/**
 * Domain model for an AI-generated daily web app.
 * Each app is a unique, interactive HTML/CSS/JS mini-application
 * generated by Claude based on the user's journal entries and emotional state.
 */
data class DailyApp(
    val id: String,
    val userId: String,
    val date: Instant,                 // Date the app was generated for
    val title: String,
    val description: String,           // Why this app was suggested
    val htmlCode: String,              // Complete HTML/CSS/JS code
    val journalContext: String?,       // Summary of relevant journal entries
    val status: DailyAppStatus,
    val usedAt: Instant?,              // When user first opened the app
    val createdAt: Instant,
    val updatedAt: Instant,
    val syncStatus: SyncStatus = SyncStatus.LOCAL_ONLY
)

/**
 * Status of a daily app from the user's perspective.
 */
enum class DailyAppStatus {
    PENDING,    // Generated but user hasn't interacted with it yet
    LIKED,      // User liked it - saved to "My Tools" library
    DISLIKED    // User disliked it - won't be shown again
}

/**
 * Domain model for app-specific key-value data storage.
 * Enables schema-less persistence for any data structure the AI-generated app needs.
 */
data class DailyAppData(
    val appId: String,
    val key: String,
    val value: String,                 // JSON-serialized value
    val updatedAt: Instant,
    val syncStatus: SyncStatus = SyncStatus.LOCAL_ONLY
)
